### ISSUE TITLE
"mean face" problem

### ISSUE THREAD

**Issue by HoiM** [xingmimfl/Deep3DFacereconstruction_pytorch3d#4]
I found that in your implementation, the first layer of ResNet-50 are frozen. (you set ```require_grad``` as ```False```), may I know the reason why you have such a setting?

**Comment by HoiM** [comment]
Problem found. Not an overfitting but a bug in my test code.

**Comment by zzhat0706** [comment]
@HoiM Sorry for bothering，I also found the mean shape problem in training process. I am wondering if you sovled this problem by set require_grad as True，to let even the first layer of Resnet trainable？Thanks.
